apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: kube-system
  labels:
    name: grafana-external
spec:
  # loadBalancerIP: 35.243.116.160
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: web
  selector:
    app: grafana
    component: core