kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-config-pvc
  namespace: mattermost
  annotations:
    volume.beta.kubernetes.io/storage-class: gcp-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi