apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mattermost
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: mattermost
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
#      affinity:
#        podAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 100
#            podAffinityTerm:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: tier
#                operator: In
#                values:
#                - frontend
#            topologyKey: kubernetes.io/hostname
#            namespaces: [concourse]
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: mattermost/mattermost-prod-db
        env:
        - name: POSTGRES_DB
          value: mattermost
        - name: POSTGRES_USER
          value: mattermost
        - name: POSTGRES_PASSWORD
          value: mattermost
        - name: PGDATA
          value: /persist/database
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /persist
      # nodeSelector:
      #   crp: default